[build]
  builder = "nixpacks"

[deploy]
  startCommand = "bash -lc \"exec python -u scheduler_refresh.py --once\""
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
